name: ci
on: push
jobs:
  tests:
    # run 3 copies of the current job in parallel
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Run split Cypress tests 🧪
        uses: cypress-io/github-action@v6
        with:
          start: npm run start${{ strategy.job-index }}
          publish-summary: false
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
